[workspace]
members = ["crates/bevy_m8"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.100"
serialport = "4.8.1"
bevy = { version = "0.18.0", default-features = false }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
